export const endPoint = {
  HOMEPAGE: "/",
  COMMUNITY: "/community",
  RESTAURANT_BOOKMARK: "/bookmarks/restaurants",
  POST_BOOKMARK: "/bookmarks/posts",
  POST: "/post",
  PACKAGE: "/package",
  CHAT: "/chat",
  AUTH: "/auth",
  LOGIN: "/auth?view=login",
  REGISTER: "/auth?view=register",
  FORGOTPASSWORD:"/auth?view=forgotPassword",
  ONBOARDING:"/onboarding",
  // User profile base and segment for nested paths
  USER_BASE: "/user",
  PROFILE: "profile",
  RESTAURANT_DETAIL: (id = ":id") => `/restaurants/${id}`,
  RESTAURANT_MENU: (id = ":id") => `/restaurants/${id}/menu`,
  RESTAURANT_REVIEWS: (id = ":id") => `/restaurants/${id}/reviews`,
   RESTAURANT_EDIT:   (id=":id") => `/restaurants/${id}/edit`,
}